apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: voting-app-metrics
  namespace: voting-app
  labels:
    app.kubernetes.io/name: voting-app
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: voting-app
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
    scrapeTimeout: 10s

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: voting-app-pods
  namespace: voting-app
  labels:
    app.kubernetes.io/name: voting-app
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: voting-app
  podMetricsEndpoints:
  - port: http
    interval: 30s
    path: /metrics
    scrapeTimeout: 10s

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: voting-app-alerts
  namespace: voting-app
  labels:
    app.kubernetes.io/name: voting-app
    release: prometheus
spec:
  groups:
  - name: voting-app
    interval: 30s
    rules:
    - alert: HighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High error rate detected"
        description: "Error rate is above 5% for the last 5 minutes"

    - alert: PodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Pod is crash looping"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is crash looping"

    - alert: HighMemoryUsage
      expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) > 0.9
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High memory usage detected"
        description: "Memory usage is above 90% for pod {{ $labels.pod }}"

    - alert: HighCPUUsage
      expr: (rate(container_cpu_usage_seconds_total[5m]) / container_spec_cpu_quota) > 0.9
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage detected"
        description: "CPU usage is above 90% for pod {{ $labels.pod }}"

    - alert: DatabaseConnectionFailure
      expr: up{job="postgresql"} == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Database connection failure"
        description: "Cannot connect to PostgreSQL database"

    - alert: RedisConnectionFailure
      expr: up{job="redis"} == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Redis connection failure"
        description: "Cannot connect to Redis"

